version: '1'

services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
      container_name: elasticsearch
      environment:
        - "discovery.type=single-node"
        - bootstrap.memory_lock=true
      ports:
        - "9200:9200"
        - "9300:9300"
      ulimits:
        memlock:
          soft: -1
          hard: -1
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    hostname: kibana
    environment: 
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
  db: 
    image: postgres
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=elastic_search_development
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  web: 
    build: .
    entrypoint: ./docker-entrypoint.sh
    ports: 
      - 3000:3000
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - .:/usr/src/app
    command: "bundle exec rails s -b 0.0.0.0"
    depends_on:
      - db
volumes:
  postgres: